--Parte 2.1 PL/SQL
SET SERVEROUTPUT ON;
CREATE SEQUENCE SQ_ERROR
INCREMENT BY 1
START WITH 1;

UPDATE PRESTAMO SET
FECHA_ENTREGA = '25/04/2016'
WHERE PRESTAMOID = 49477;

UPDATE PRESTAMO SET
FECHA_ENTREGA = '05/01/2016'
WHERE PRESTAMOID = 30564;

UPDATE PRESTAMO SET
FECHA_TERMINO = '26/04/2016',
FECHA_ENTREGA = '06/05/2016'
WHERE PRESTAMOID = 84659;

CREATE OR REPLACE PACKAGE PKG_PRO IS
FUNCTION FN_OBTENER_PORC_MULTA(PRES NUMBER,V_AU NUMBER) RETURN NUMBER;
FUNCTION FN_OBTENER_MULTA(PRES NUMBER,V_AU NUMBER)RETURN NUMBER;
END PKG_PRO;

CREATE OR REPLACE PACKAGE BODY PKG_PRO IS
FUNCTION FN_OBTENER_PORC_MULTA
(PRES NUMBER,V_AU NUMBER) RETURN NUMBER
IS V_PORC NUMBER;
V_AUX NUMBER(4) := V_AU;
ERR_CODE NUMBER(5);
ERR_MSG VARCHAR2(64);
BEGIN
IF V_AUX <= 0 THEN
V_AUX := 0;
END IF;
SELECT PORCENTAJE_MULTA INTO V_PORC
FROM PORC_MULTA_PRESTAMO WHERE V_AUX >= CANT_DIAS_INI AND
V_AUX <= CANT_DIAS_TER;

RETURN V_PORC;
EXCEPTION
WHEN NO_DATA_FOUND THEN
    ERR_CODE:=SQLCODE;
    ERR_MSG:=SUBSTR(SQLERRM,1,64);
    INSERT INTO ERRORES VALUES(
    SQ_ERROR.NEXTVAL,
    'Error al obtener porcentajes de MULTA:'||PRES,
    ERR_CODE||' '||ERR_MSG);
    RETURN 0;
END FN_OBTENER_PORC_MULTA;

FUNCTION FN_OBTENER_MULTA(PRES NUMBER,V_AU NUMBER)RETURN NUMBER
IS V_NMUL NUMBER;

BEGIN
SELECT (MULTA+((MULTA*V_AU)/100)) INTO V_NMUL FROM PRESTAMO WHERE PRESTAMOID = PRES;
RETURN V_NMUL;
END;

END PKG_PRO;

CREATE OR REPLACE PROCEDURE SP_MULTA IS
CURSOR CUR_REG IS SELECT PRESTAMOID,FECHA_TERMINO,FECHA_ENTREGA,MULTA,GLOSA_MULTA FROM PRESTAMO;
V_PORC NUMBER(3) := 0;
V_NMULTA NUMBER(7) := 0;
V_GMULTA VARCHAR2(100);
V_AUX NUMBER(2) := 0;

BEGIN 
FOR REG_PRO IN CUR_REG LOOP
V_AUX := REG_PRO.FECHA_ENTREGA-REG_PRO.FECHA_TERMINO;
V_PORC := PKG_PRO.FN_OBTENER_PORC_MULTA(REG_PRO.PRESTAMOID,V_AUX);
V_NMULTA := PKG_PRO.FN_OBTENER_MULTA(REG_PRO.PRESTAMOID,V_PORC);
V_GMULTA := 'El valor de la multa se aumento por '||V_PORC||' Dias de atraso';
IF V_PORC > 0 THEN
UPDATE PRESTAMO SET
MULTA = V_NMULTA,
GLOSA_MULTA = V_GMULTA
WHERE PRESTAMOID =REG_PRO.PRESTAMOID;
END IF;
END LOOP;
END;

EXEC SP_MULTA;

--Parte 2.2 PL/SQL
CREATE SEQUENCE SQ_CORRELATIVO_PRES
INCREMENT BY 1
START WITH 1;

CREATE OR REPLACE PROCEDURE SP_PRESTAMOS_LIBROS_MENSUALES
IS CURSOR CUR_REG IS 
SELECT DISTINCT
P.PRESTAMOID
,T.TITULO,
ED.DESCRIPCION as descEDI,
AU.NOMBRE||' '||AU.APELLIDOS as Nombre_autor,
A.NOMBRE||' '||A.APATERNO||' '||A.AMATERNO as nombre_alu,
E.DESCRIPCION as descesc,C.DESCRIPCION as desccar,
EM.NOMBRE||' '||EM.APATERNO||' '||EM.AMATERNO as nombre_emp,
P.FECHA_INICIO,
P.FECHA_TERMINO,
P.FECHA_ENTREGA
FROM PRESTAMO P JOIN ALUMNO A
ON(P.ALUMNOID = A.ALUMNOID)JOIN CARRERA C
ON(A.CARRERAID = C.CARRERAID)JOIN ESCUELA E
ON(C.ESCUELAID = E.ESCUELAID)JOIN EJEMPLAR EJ
ON(P.EJEMPLARID = EJ.EJEMPLARID)JOIN TITULO T
ON(EJ.TITULOID = T.TITULOID)JOIN AUTOR AU
ON(T.TITULOID = AU.TITULOID) JOIN EDITORIAL ED
ON(T.EDITORIALID = ED.EDITORIALID)JOIN EMPLEADO EM
ON(P.EMPLEADOID = EM.EMPLEADOID);
V_AUX NUMBER(3) := 0;
V_PORC NUMBER(5) :=0;
V_NMULTA NUMBER(8) := 0;
ERR_CODE NUMBER(5);
ERR_MSG VARCHAR2(64);
BEGIN
FOR REG_PRO IN CUR_REG LOOP
V_AUX := REG_PRO.FECHA_ENTREGA-REG_PRO.FECHA_TERMINO;
V_PORC := PKG_PRO.FN_OBTENER_PORC_MULTA(REG_PRO.PRESTAMOID,V_AUX);
V_NMULTA := PKG_PRO.FN_OBTENER_MULTA(REG_PRO.PRESTAMOID,V_PORC);
INSERT INTO PRESTAMOS_LIBROS_MENSUALES
VALUES(SQ_CORRELATIVO_PRES.NEXTVAL,
'06/2016',
REG_PRO.TITULO,
REG_PRO.descEDI,
REG_PRO.Nombre_autor,
REG_PRO.nombre_alu,
REG_PRO.descesc,
REG_PRO.desccar,
REG_PRO.nombre_emp,
REG_PRO.FECHA_INICIO,
REG_PRO.FECHA_TERMINO,
REG_PRO.FECHA_ENTREGA,
V_AUX,
V_NMULTA,
SYSDATE);
END LOOP;
END;

EXEC SP_PRESTAMOS_LIBROS_MENSUALES;

ROLLBACK;
select * from PRESTAMOS_LIBROS_MENSUALES;
