CREATE OR REPLACE PROCEDURE SP_BONIFICACION
IS
rut EMPLEADO.RUT_EMPLEADO%TYPE;
mes NUMBER(1);
anno NUMBER(4);
comven NUMBER(9);
bonanti NUMBER(9);
CURSOR cur_emp IS
SELECT RUT_EMPLEADO FROM EMPLEADO;
BEGIN 

FOR reg_pro IN cur_emp LOOP
SELECT reg_pro.RUT_EMPLEADO
,5 MES
,2014 ANNO
,
FN_BONO_ANTIGUEDAD(reg_pro.RUT_EMPLEADO),
FN_CALC_COMISION(reg_pro.RUT_EMPLEADO) 
INTO
rut,
mes,
anno,
comven,
bonanti
FROM VENTAS_MES v RIGHT OUTER JOIN EMPLEADO E
ON(v.RUT_EMPLEADO=E.RUT_EMPLEADO)
group by reg_pro.RUT_EMPLEADO;


INSERT INTO BONIFICACIONES
VALUES(rut,mes,anno,comven,bonanti);
END LOOP;
END;

EXEC SP_BONIFICACION;

