CREATE OR REPLACE FUNCTION FN_CALC_COMISION
(rut VENTAS_MES.RUT_EMPLEADO%TYPE)
RETURN NUMBER IS
TOTAL NUMBER(8);

BEGIN
select ROUND(0.125*(NVL(SUM(v.MONTO_TOTAL),0)))
INTO TOTAL
FROM VENTAS_MES v RIGHT OUTER JOIN EMPLEADO E
ON(v.RUT_EMPLEADO=E.RUT_EMPLEADO)
WHERE E.RUT_EMPLEADO=rut
GROUP BY E.RUT_EMPLEADO;

RETURN TOTAL;
END FN_CALC_COMISION;

SELECT E.RUT_EMPLEADO,FN_CALC_COMISION(E.RUT_EMPLEADO) 
FROM VENTAS_MES v RIGHT OUTER JOIN EMPLEADO E
ON(v.RUT_EMPLEADO=E.RUT_EMPLEADO)
group by E.RUT_EMPLEADO;
