CREATE OR REPLACE PROCEDURE SP_BONIFICACION
IS
rut EMPLEADO.RUT_EMPLEADO%TYPE;
mes NUMBER(1);
anno NUMBER(4);
comven NUMBER(9);
bonanti NUMBER(9);
CURSOR cur_emp IS
SELECT RUT_EMPLEADO FROM EMPLEADO;
BEGIN 

FOR reg_pro IN cur_emp LOOP
SELECT reg_pro.RUT_EMPLEADO
,5 MES
,2014 ANNO
,
FN_BONO_ANTIGUEDAD(reg_pro.RUT_EMPLEADO),
FN_CALC_COMISION(reg_pro.RUT_EMPLEADO) 
INTO
rut,
mes,
anno,
comven,
bonanti
FROM VENTAS_MES v RIGHT OUTER JOIN EMPLEADO E
ON(v.RUT_EMPLEADO=E.RUT_EMPLEADO)
group by reg_pro.RUT_EMPLEADO;


INSERT INTO BONIFICACIONES
VALUES(rut,mes,anno,comven,bonanti);


END LOOP;
EXCEPTION
    WHEN OTHERS THEN
    ERR_CODE:=SQLCODE;
    ERR_MSG:=SUBSTR(SQLERRM,1,64);
END;

EXEC SP_BONIFICACION;

CREATE TABLE ERRORES_PROCESOS_DUMBO
(SEC_ERROR NUMBER(5) NOT NULL PRIMARY KEY,
SUB_PROGRAMA VARCHAR2(20) NOT NULL,
MENSAJE VARCHAR2(200) NOT NULL);

CREATE SEQUENCE SEC_ERROR_N
INCREMENT BY 1
START WITH 1;

EXCEPTION
    WHEN OTHERS THEN
    ERR_CODE:=SQLCODE;
    ERR_MSG:=SUBSTR(SQLERRM,1,64);
    INSERT INTO ERROR_CALC_REMUN VALUES(
    SEQ_ERROR.NEXTVAL,
    'Error al obtener porcentajes de comision de colacion. Vendedor: '||TMP.NOM,
    'COD: '||ERR_CODE||' '||ERR_MSG);
    POR_COMI:=0;